#!/bin/bash

PROJECT_PATH="`pwd $(dirname $0)`"

SRC_PATH=$PROJECT_PATH'/src'

TARGET_PATH=$PROJECT_PATH'/target'

cmd() {
    CMD="gm convert $1 +profile '*' -thumbnail '$2' $3"
    echo "$CMD"
    eval $CMD
}

function files() {
    RANGE=$1
    if [[ -z "$RANGE" ]]; then
        RANGE=960
    fi
    for file in `ls $SRC_PATH`
    do
        if [ -f  $SRC_PATH"/"$file ]
        then
            cmd $SRC_PATH"/"$file $RANGE $TARGET_PATH"/"$file
        fi
    done
}


case $1 in
    *)
        files "$@"
        ;;
esac
